### ISSUE TITLE
保存的快捷键和tab键

### ISSUE THREAD

**Issue by puttiko** [akof1314/Wiz.Editor.md#10]
习惯边写边按`Ctrl+S`保存，但是发现在这个编辑器下这个快捷键不起作用。

另外，按`Tab`键没有反应，不知道是不是我一个人遇到的问题？

**Comment by akof1314** [comment]
@puttiko 在编辑区按Ctrl+S是能够保存的。但是Tab键被为知拦截了，我改成F1键代替了。

**Comment by puttiko** [comment]
@akof1314 谢谢，重新试了一下，在打开同步预览的时候可以按`Ctrl+S`保存，关掉同步预览的时候无用。

**Comment by akof1314** [comment]
@puttiko 嗯，是有这个情况。下个版本修复。
