### ISSUE TITLE
bug fixed:用原生编译器插入的图片显示位置不正确

### ISSUE THREAD

**Issue by zssty2010** [akof1314/Wiz.Editor.md#100]
[https://github.com/akof1314/Wiz.Editor.md/blob/master/md_editor_core.js#L575](https://github.com/akof1314/Wiz.Editor.md/blob/master/md_editor_core.js#L575)
使用appendChild会导致图片位置发生改变，实事上总是在最后。

修改为：**$(pi).replaceWith(imgmd);**

editor.md已经是引入了jquery的，所以使用它的repalceWith方法更通用。

**Comment by akof1314** [comment]
@zssty2010 好的 谢谢
