### ISSUE TITLE
列表中插入代码框，代码框后的二级列表在编辑器的语法高亮中被视作代码框

### ISSUE THREAD

**Issue by QIEXXII** [akof1314/Wiz.Editor.md#102]
举个栗子：
![image](https://cloud.githubusercontent.com/assets/16456434/22637555/677bcc76-ec7d-11e6-9d33-6ec2438d37d8.png)
上图示例代码：
```
### Nesting elements(嵌套元素)
You can put elements inside other elements — this is called nesting（嵌套）
* e.g..
    ```
    <p>My cat is <strong>very</strong> grumpy.</p>
    ```
    * we opened the `<p>` element first, then the `<strong>` element, therefore we have to close the `<strong>` element first, then the `<p>`.
```

**Comment by akof1314** [comment]
需要空行才好解析。

**Comment by akof1314** [comment]
![image](https://cloud.githubusercontent.com/assets/2639552/24328743/bdfc0c42-1224-11e7-8b59-fb28608a655f.png)
已经更新CodeMirror
