### ISSUE TITLE
请问可否支持TOC输出为类似普遍的博客样式的侧边栏呢

### ISSUE THREAD

**Issue by ivlydp** [akof1314/Wiz.Editor.md#103]
目前TOC生成的样式是顶部链接，文章较长的话跳转不方便。不知作者是否有精力实现此功能呢？

**Comment by akof1314** [comment]
是说在编辑模式下吗？在编辑模式下的话，工具栏有个大纲按钮，可以方便跳转。

**Comment by ivlydp** [comment]
最终渲染可以实现吗？比如说md文件较长时浏览的过程中跳转会变得很麻烦，使用TOC需要跳转到文章开头再进行跳转，如果有一个侧边栏那么就会方便许多

**Comment by akof1314** [comment]
最终渲染的时候，为知有个大纲插件了，可以点大纲来跳转
