### ISSUE TITLE
编辑器工具栏显示不正常

### ISSUE THREAD

**Issue by frostnova0** [akof1314/Wiz.Editor.md#105]
作者你好，用的最新的4.6.2版本，改了设置用的便携模式，然后发现编辑器显示成这样了
![1](https://cloud.githubusercontent.com/assets/7018852/23902615/c025f838-08fc-11e7-8222-8beacf71e652.png)，能帮忙看一下是哪里出了问题么，谢谢

**Comment by akof1314** [comment]
先重启试试，不行的话再重新安装下为知

**Comment by frostnova0** [comment]
我觉得是版本的问题，在公司也试了一下，4.6版也是显示错误，晚上回去用旧版测试一下

**Comment by akof1314** [comment]
非便携模式的话，我这边4.6.2是工具栏显示正常

**Comment by frostnova0** [comment]
找出来问题了，是字体，把包里的字体安装了一遍就正常了
