### ISSUE TITLE
列表项空行导致滚动到页首的问题

### ISSUE THREAD

**Issue by pot-code** [akof1314/Wiz.Editor.md#108]
又是我....然后问题描述：

如果两个列表项（使用"-"语法创建的列表项）之间出现了空行，那么预览界面滚动到这部分的时候，再往下滚动会导致预览页面跳转到开头位置（回到顶部的效果），不知道是我的语法习惯不正确还是bug，可能的示例文本如下：

```
//一些文本//

- 列表项1
//空行
- 列表项2
```

**Comment by akof1314** [comment]
我这边没有复现出来，可以提供测试文本吗？

**Comment by pot-code** [comment]
@akof1314

应该是历史版本的问题吧，我现在更新了版本问题就没有了。前端时间因为某种原因更新一直装不了新版本，刚才测试显示已经没问题了，可以close了;)
