### ISSUE TITLE
第一次发issue, 放上支付宝或者微信的支付二维码吧.

### ISSUE THREAD

**Issue by OLetsGame** [akof1314/Wiz.Editor.md#110]
第一次发issue, 如果不得当请删除.
放上支付宝或者微信的支付二维码吧.
一直用为知笔记的md, 非常喜欢你这个项目, 想打赏几十块钱表示感谢.

**Comment by akof1314** [comment]
@OLetsGame 谢谢支持，之前有考虑过，但一直没放上去
