### ISSUE TITLE
从word复制后粘贴会粘贴两次

### ISSUE THREAD

**Issue by zichenw** [akof1314/Wiz.Editor.md#111]
比如这样一段话**私钥（private key）存储于客户端**从word复制出来后粘到MD编辑器里变成**私钥（private key）存储于客户端私钥（private key）存储于客户端**
2.2版本好像是没这问题的，装了2.3出现的

**Comment by QIEXXII** [comment]
我也遇到了这个问题，2333

**Comment by akof1314** [comment]
我再检查检查下

**Comment by YQ-YD** [comment]
遇到了同样的问题 我这个是不管从哪里复制 粘贴进去都会变成两遍

**Comment by wmaqingbo** [comment]
+1。不管从哪里复制 粘贴进去都会变成两遍，目前使用的最新版本。

**Comment by hijeffery** [comment]
遇到了同样的问题 每次需要选择无格式黏贴 Ctrl+Shift+v 才能避免，略麻烦

**Comment by iningmeng** [comment]
我也遇到这种问题了，都是粘帖两遍
