### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by zc58778560** [akof1314/Wiz.Editor.md#118]
#### 为知 4.8.1，Editor.md v2.3
每次新建一个`*.md`文件，然后用 Editor.md编辑器 打开，会出现2个空行（按照正常逻辑，应该只有1个空行才对）。

![capture](https://user-images.githubusercontent.com/10148442/27981290-bdf26658-63bc-11e7-81f0-0498bae88eb7.png)

**Comment by akof1314** [comment]
收到

**Comment by akof1314** [comment]
新建的时候，新笔记都带了换行符，所以用 Editor.md 打开会两行
