### ISSUE TITLE
有计划支持笔记内链吗？

### ISSUE THREAD

**Issue by laphylee** [akof1314/Wiz.Editor.md#119]
现在用Editor.md打开一个原先有内链的笔记，内链会变成纯文本。保存后原先的内链就消失了。这导致我就不敢吧Editor.md当成默认的编辑器了。

**Comment by akof1314** [comment]
会尝试加下

**Comment by laphylee** [comment]
多谢！

**Comment by akof1314** [comment]
![image](https://user-images.githubusercontent.com/2639552/30779829-20b4725a-a12e-11e7-8eb1-a95fea6b02e3.png)
内链的话，要用这种方式

**Comment by laphylee** [comment]
谢谢！但用Editor.md打开一个原先有内链的笔记（用原生markdown生成的），内链会变成纯文本。是吧？

**Comment by akof1314** [comment]
目前是的，原先的内链方式也不是标准的Markdown写法

**Comment by zhangyu0806** [comment]
在 Editor.md 阅读窗口中点击内链，弹出一个空白页面，没有内容。超爱这个插件，这个后续会解决吗？

**Comment by akof1314** [comment]
@zhangyu0806 解决了，在之后的2.7版本

**Comment by laphylee** [comment]
Wow~ 2.7什么时候release？
