### ISSUE TITLE
粘贴图片的形式

### ISSUE THREAD

**Issue by zhongwangninja** [akof1314/Wiz.Editor.md#12]
1. 使用wiz原生md笔记时, 图片都是直接粘贴上去的, 如果用Wiz.Editor.md 打开, 这些图片会无法显示, 或者直接丢失;
1. 使用Wiz.Editor.md来创建md文件时, 可以用![](D:\box\pic\)这种形式, 添加本地文件, 在本地查看笔记ok, 但是如果同步到其他端, 就会出现问题, 能否考虑以附件的形式来添加, 每次在笔记中添加图片会自动记录下这个图片的相对路径, ![](D:\box\pic\)中自动生成这个图片的相对路径, 这种图片也会被同步到为知云上.

感谢提供这么优秀的插件.

**Comment by akof1314** [comment]
1. 原生笔记直接粘贴图片的方式，其实并不是标准的添加图片方式，存的是html代码，而不是纯文本，所以用Wiz.Editor.md 打开，会被过滤掉。不建议用这种方式添加图片。
2.在本地查看OK，在其他端查看不OK，是因为他们采用了不同的处理方式，所以做为第三方插件来做这些就比较难以达到。但是这些图片是不会丢的，是有保存在服务器的，只是在其他端没正常显示。后期如果实在没办法解决，可能会考虑附件形式插入图片。

**Comment by xmfan2000** [comment]
为知的编辑器，直接粘贴图片还是很方便的。用代码的方式贴图片，一是麻烦，而是不够直观。

**Comment by akof1314** [comment]
@xmfan2000 Markdown笔记不建议这样子，作为纯文本格式的书写方式，这样子不能复制粘贴到外部。

**Comment by xmfan2000** [comment]
@akof1314 纯文本的格式保留，再多一种方式不是更好嘛。markdown各方面都挺好的，就是插图片这块真是比较麻烦，我们用工具的目的就是为了方便，不是吗？至于说复制粘贴到外部的问题，对应的图片文件也要单独复制过去的，目前图片应该是保存在为知的压缩文件中的，要把图片文件复制出来还是相当麻烦的。^_^

**Comment by zhongwangninja** [comment]
@akof1314 
1. 为知这种快速粘贴图片的方式, 确实和markdown语法很不搭, 在向其他的markdown平台迁移的时候图片很容易丢失;
1. 如果能支持附件图片, 然后用![](附件路径), 这种形式来解决还是很赞的, 给你这个解决方案点个赞.
