### ISSUE TITLE
图片丢失问题

### ISSUE THREAD

**Issue by ribber** [akof1314/Wiz.Editor.md#122]
使用 Wiz.Editor.md 插件编辑并插入的图片，在以下情况会丢失
- 使用 Wiz 自带的内部编辑器或其他编辑器编辑并保存后
- 没有保存 Wiz.Editor.md 编辑的内容，点击 `X` 关闭，弹出“是否保存更改”的提示，并选择“否”
- 复制或剪切带有图片的一段内容到另一个笔记，另一个笔记的这段内容中的图片会丢失

![image](https://user-images.githubusercontent.com/5986011/28254874-88383d84-6ae3-11e7-9036-6819b1d0994c.png)

注意：因为 Wiz 会缓存 markdown 文件渲染后的结果，所以图片丢失之后不太容易发现，除非同步到其他客户端查看

**Comment by ribber** [comment]
问题 2 是否保存更改 的问题可以改进下哈

**Comment by Kongz233** [comment]
第一个问题我这边测试过，没出现
第三个问题可能是因为你的图片用的是相对链接，类似于这种：![](index_files/0.27368640006158906.png)
而且貌似wiz的ios版不支持渲染图片链接
ps：我不是这个插件的开发人员，只是普通用户

**Comment by ribber** [comment]
第一个问题是被广泛测试的，这个是大家都知道的，编辑器不能混用
第三个问题跟ios没关系
我本身也是搞开发的

**Comment by akof1314** [comment]
1. 在最新版修改了隐藏图片的标签，减少被手动删掉的可能
2. 最新版修复
3. Markdown笔记复制剪切到另一个笔记，图片路径是识别不到的
