### ISSUE TITLE
Ctrl+V之后，复制的内容被粘贴两次

### ISSUE THREAD

**Issue by HuskyThink** [akof1314/Wiz.Editor.md#124]
复制的文本“想买什么，想吃什么，反正就是一定要，在一时痛快后才后悔不已”

粘贴后变成“想买什么，想吃什么，反正就是一定要，在一时痛快后才后悔不已想买什么，想吃什么，反正就是一定要，在一时痛快后才后悔不已”

粘贴到别的地方，还是正常的一句话。

插件版本：2.3
为知版本：4.7.1001
操作系统：WIN7 64位旗舰版、WIN10 64位企业版

**Comment by 9527dong** [comment]
是的，我也有这个问题

**Comment by xzl2021** [comment]
没错，我也是这个情况。

**Comment by AL0N4K** [comment]
应该建议增加一个纯文本粘贴模式.

**Comment by akof1314** [comment]
收到~  目前是有纯文本粘贴模式的，也可以使用快捷键Ctrl+Shift+v的纯文本粘贴

**Comment by akof1314** [comment]
参见 #111
