### ISSUE TITLE
插入代码中含有 # 预览时被渲染为标题

### ISSUE THREAD

**Issue by Xenaxxx** [akof1314/Wiz.Editor.md#132]
现象：

![default](https://user-images.githubusercontent.com/4945218/29953909-5f518bfe-8f06-11e7-954d-a7549c37a9ba.png)

另：这个是被渲染为 emoji 之类的然而没有图片？

![image](https://user-images.githubusercontent.com/4945218/29953792-91084fc6-8f05-11e7-90b6-401fcf0afe96.png)

**Comment by akof1314** [comment]
@Xenaxxx 示例文本可以贴一下，让我来测试下吗？

**Comment by Xenaxxx** [comment]
@akof1314  

## 配置 Mysql 链接
 1. 打开src/main/resources目录下的application.properties，输入MySQL的配置信息
 ```
 spring.datasource.url=jdbc:mysql://localhost/test
 spring.datasource.username=root
 # 下面的配置为官网提供的一些配置参数
 
 ```

**勘误：** 第一个问题截图上的 code 语法，似乎写错了符号，才导致 code 中的注释被渲染为 标题1 ，因此不是  Bug。

**Comment by akof1314** [comment]
第二个的话，可以在设置那边关掉表情
