### ISSUE TITLE
表情符渲染问题

### ISSUE THREAD

**Issue by ddcatgg** [akof1314/Wiz.Editor.md#133]
表情符渲染问题
---------------------------------
Wiz.Editor.md 插件，我设置了不显示表情符，编辑的时候看预览窗口是生效了，但退出编辑后渲染还是会显示表情符，一大段代码中突然显示出表情符的情景太烦人了。

通过官方调试说明（Wiz.exe命令行加/debug参数）按F12调试插件，发现如图的初始化对象失败，所以后面使用对象读取表情符设置的功能出了问题。

![image1](https://user-images.githubusercontent.com/8475003/29996195-7182d248-902c-11e7-836a-2e328eb43679.png)

请帮忙解疑，谢谢！

为知笔记版本：Wiz Windows版 v4.8.4.0

**Comment by Xenaxxx** [comment]
@akof1314  关闭表情之后也不行呀

**Comment by akof1314** [comment]
读取配置出了问题，新版已修复

**Comment by ddcatgg** [comment]
@akof1314 新版修复了？太好了，那如果真的修复了，就可以关闭这个issue了。谢谢！
