### ISSUE TITLE
希望添加点击截图按钮之后自动最小化为知窗口的功能

### ISSUE THREAD

**Issue by AzusaMoe** [akof1314/Wiz.Editor.md#134]
本来打算自己改了再pull的，结果克隆下来就懵逼了，不会js，只能来提建议了
希望点击截图按钮之后，能最小化为知笔记，或者说增加一个全局快捷键，这样会方便很多。本来截图内容直接添加在编辑器里很方便，但是截图之前不把为知窗口拖小就根本没有意义。

**Comment by akof1314** [comment]
@AzusaMoe 这个需要为知来支持，js插件无法做到最小化为知窗口呢
