### ISSUE TITLE
怎么进入 vim 模式，按 ctrl + [  没反应。

### ISSUE THREAD

**Issue by zhangyu0806** [akof1314/Wiz.Editor.md#137]
昨天刚更新的 wiz 新版，4.9.3

**Comment by akof1314** [comment]
@zhangyu0806 需要先在设置界面开启 vim 的键盘方式

**Comment by zhangyu0806** [comment]
……这个马虎，没注意到。

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/47250236-da50ca00-d450-11e8-9d44-065a81fcc06b.png)


找了半天不知道怎么开启`Vim`模式呢，QAQ

还有使用`Editor.md`编辑器编辑，也没找到，跪求指导。。。

![image](https://user-images.githubusercontent.com/9500049/47250265-33b8f900-d451-11e8-85ff-588d93f24053.png)

**Comment by initialneil** [comment]
同找不到怎么开启 VIM，同问
