### ISSUE TITLE
只要安装插件, 为知内置的markdown渲染预览只输出纯文本.

### ISSUE THREAD

**Issue by harrisyu** [akof1314/Wiz.Editor.md#138]
只要安装插件, 为知内置的markdown渲染预览只输出纯文本.
不知道是哪里问题, 禁用插件重启又恢复正常.

**Comment by akof1314** [comment]
@harrisyu 为知的版本号，插件的版本号？？

**Comment by harrisyu** [comment]
今天为知更新到4.9.3版本后，问题消失。
