### ISSUE TITLE
文本区块引用显示有问题

### ISSUE THREAD

**Issue by spartawhy117** [akof1314/Wiz.Editor.md#14]
![image](https://cloud.githubusercontent.com/assets/9450028/9013822/ebbcf7fa-37f0-11e5-998e-5dad0cc3b3ab.png)

原本文本区块引用该这显示：
 >  文本引用显示不正确

现在是这样显示：

`>  文本引用显示不正确
`

不知道这个是为知笔记的markdown语法的bug还是插件的原因，希望能够解决一下。还有代码块引用缩进风格如何增加显示行号？

**Comment by akof1314** [comment]
@spartawhy117 我这边没有出现这样的情况，>右边是空格，还是其他不可见字符？

代码块引用缩进风格会自动显示行号。

**Comment by spartawhy117** [comment]
> 右边是空格，不知道你的为知笔记的版本是多少？
还有代码引用块缩进风格我的没有显示行号不知道是什么情况。
如果方便的话，想要加您的QQ学习一下。我的Q号就是我github上邮箱信息里的Q号，谢谢了

**Comment by spartawhy117** [comment]
根据我目前查的的情况来看，有可能是为知笔记内部markdown语法渲染出现了问题。不知道您目前的版本是多少

**Comment by spartawhy117** [comment]
刚刚试了一下禁用了为知笔记自带的markdown插件和设置了editor.md编辑器渲染风格，但是问题依旧。
![image](https://cloud.githubusercontent.com/assets/9450028/9021117/bae120b0-3864-11e5-904a-ada5a1d94c46.png)

可以看到使用缩进代码块显示依然没有行号，不知道什么原因。

**Comment by spartawhy117** [comment]
现在已经解决，些许的格式差异会导致上面的情况发生，我重新调整了一下引用段落上面的格式和发现又恢复正常了。具体有什么差异还不清楚。

**Comment by akof1314** [comment]
@spartawhy117 是否由外部复制进来引起的？可以开启‘纯文本粘贴’模式，试试看会不会正常。

**Comment by spartawhy117** [comment]
应该不是，后来我自己重写打了一段引用还是没成功。后来是调整了一下格式才正确显示的。可能是格式不太正确。

**Comment by akof1314** [comment]
@spartawhy117 好的。
