### ISSUE TITLE
代码换行缩进问题

### ISSUE THREAD

**Issue by xiao2752271456** [akof1314/Wiz.Editor.md#140]
![image](https://user-images.githubusercontent.com/30465802/31765506-32ae7708-b4f7-11e7-93c3-a5bba5d45239.png)

在`const int a;` 之后输入换行后, 下一行跑前面去了.
求解,谢谢

**Comment by akof1314** [comment]
@xiao2752271456 收到，2.6版本修复

**Comment by xiao2752271456** [comment]
Tks
