### ISSUE TITLE
vim 模式下 esc 键与为知笔记本身热键冲突

### ISSUE THREAD

**Issue by nemo-nullius** [akof1314/Wiz.Editor.md#141]
您好，首先非常感谢您的markdown插件，一直在用，很喜欢。

最近在用时发现在 vim 模式下有个小问题。每当我按下 esc 时，由于为知笔记本身对 esc 键做了设定，所以 esc 键激活的是为知笔记本身的设定 - "显示/隐藏左侧目录栏"，而非 vim 下的从插入模式返回普通模式。我查看了为知笔记本身的热键选项，未见对 esc 键的设定。不知这一问题有没有什么办法解决或绕过呢？谢谢您！

**Comment by zhangyu0806** [comment]
`ctrl + [` 进入 normal 模式

**Comment by akof1314** [comment]
@nemo-nullius 没法更改为知的热键，只能使用`ctrl + [`来替代

**Comment by nemo-nullius** [comment]
@zhangyu0806 @akof1314 好的，多谢！
