### ISSUE TITLE
预览区笔记内链无法跳转

### ISSUE THREAD

**Issue by zhangyu0806** [akof1314/Wiz.Editor.md#144]
为知笔记中复制内链，在 Editor.md 中粘贴为：`[422Listening](wiz://open_document?guid=c468201f-f263-484a-b50f-1737cdee67b8&kbguid=&private_kbguid=c20deb0d-373f-11df-b822-3cc839c01a40) `

在 Editor.md 预览区中点击内链会在新窗口打开一个空白页。保存后在为知阅读模式下正常可以跳转到另一个笔记。

**Comment by akof1314** [comment]
修改在2.7版本
