### ISSUE TITLE
Zepto is not defined

### ISSUE THREAD

**Issue by shuaijunlan** [akof1314/Wiz.Editor.md#147]
#在windows上部署访问没问题，在centos7上部署访问出现如下问题：
`"ReferenceError: Zepto is not defined
    at eval (eval at <anonymous> (https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/Editor.md/editormd.js:43:58), <anonymous>:1:1)
    at https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/Editor.md/editormd.js:43:58
    at https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/Editor.md/editormd.js:34:27
    at https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/Editor.md/editormd.js:37:2"`
[在线链接https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/index.html](https://shuaijunlan.cn/autumn-blog/Lib/Wiz.Editor.md/index.html)

**Comment by akof1314** [comment]
暂时没有部署到其他地方过
