### ISSUE TITLE
请问如何替换系统默认浏览用的markdown引擎

### ISSUE THREAD

**Issue by lagunazeng** [akof1314/Wiz.Editor.md#15]
多谢作者写了这么好的工具，但是现在发现一个问题。编辑的时候都没有问题，但是wiz系统默认的markdown阅读引擎没有支持editor.md这么多东西，所以有些东西会乱掉。请教作者如何用wiz.editor.md作为wiz的默认markdown阅读解释引擎呢？

**Comment by akof1314** [comment]
@lagunazeng 工具栏上的“选项”按钮，可以设置。

**Comment by lagunazeng** [comment]
看到了，已经设置成功，非常感谢！

**Comment by yinxufeng** [comment]
@lagunazeng 在哪里，我没有找到。是这里？
![qq 20150817192008](https://cloud.githubusercontent.com/assets/1935092/9303891/187f258e-4515-11e5-8998-a5a1028c50ad.jpg)

**Comment by akof1314** [comment]
@yinxufeng 在Wiz.Editor.md打开笔记时，上面的工具栏按钮，右侧的“选项”按钮。

**Comment by yinxufeng** [comment]
@akof1314 找到了，谢谢。原来我装的不是最新版。从wiz应用里面下的还是1.2版本
