### ISSUE TITLE
win10无法安装

### ISSUE THREAD

**Issue by disanrencheng** [akof1314/Wiz.Editor.md#157]
![error](https://user-images.githubusercontent.com/18670782/37238409-97ae3304-2460-11e8-9688-98c27378f27a.png)
我用的是win10专业版
![system](https://user-images.githubusercontent.com/18670782/37238421-cbb21332-2460-11e8-97bf-ee64c71ab887.png)

**Comment by akof1314** [comment]
用手动安装方式：先用解压软件解压插件，然后把解压后的文件夹，放到为知的插件目录。
