### ISSUE TITLE
内嵌HTML标签，会被自动增加为新的P标签

### ISSUE THREAD

**Issue by yinxufeng** [akof1314/Wiz.Editor.md#16]
issues我已经提交到editor.md上了https://github.com/pandao/editor.md/issues/139
不过上面好像已经累积了很多没有处理了，可能作者比较忙。
不知道@akof1314 看看能不能解决呢

**Comment by yinxufeng** [comment]
临时解决方法，在前面加空格
![image](https://cloud.githubusercontent.com/assets/1935092/9323740/66e13838-45b6-11e5-81a5-0bef47cec1f4.png)

**Comment by akof1314** [comment]
@yinxufeng 暂时先用你说的临时方法。
