### ISSUE TITLE
编辑过的markdown笔记会将为知的默认样式删除

### ISSUE THREAD

**Issue by wizxuehz** [akof1314/Wiz.Editor.md#162]
为知创建的笔记会有一个默认样式，id是"wiz_custom_css"，在用editor.md编辑过之后，会将这个样式删除，影响笔记的显示效果

**Comment by akof1314** [comment]
因为Markdown笔记比较纯粹，所以就只保存了纯HTML，不知删了这个样式有什么显示的差异呢，目前在PC上看不出来~

**Comment by wizxuehz** [comment]
这个样式是为知全端适用的样式，比如字体，字号，行间距等，删除这个字段，笔记在各终端的显示效果会不好。为了避免给网页生成的笔记造成样式干扰，此字段不会强制添加，所以请你修改一下插件，不要删除这个样式。
