### ISSUE TITLE
这段数学公式不能正常预览

### ISSUE THREAD

**Issue by x-hey** [akof1314/Wiz.Editor.md#163]
```
$$\begin{array}{llllll}
              &               &               &                & A_{1} = [-1,0]   & A_{2} = [0,1]  \\
              &               & A_{3} = A_{1} & A_{4} = A_{2}  & A_{5} = [-2,-1]  & A_{6} = [1,2]  \\
A_{7} = A_{1} & A_{8} = A_{2} & A_{9} = A_{5} & A_{10} = A_{6} & A_{11} = [-3,-2] & A_{12} = [2,3] \\
\cdots        &               &               &                &                  &
\end{array}$$
```
![snipaste_2018-05-22_20-04-38](https://user-images.githubusercontent.com/31833775/40361313-76589f30-5dfb-11e8-88d7-6d73fb98c5aa.png)

![snipaste_2018-05-22_20-04-54](https://user-images.githubusercontent.com/31833775/40361552-4d8e0e72-5dfc-11e8-8267-8867a38c4b1d.png)

**Comment by akof1314** [comment]
![image](https://user-images.githubusercontent.com/2639552/40882623-66116ada-671a-11e8-9dc8-20ecac3f8db9.png)
将数字公式单独一段来显示看看

**Comment by x-hey** [comment]
好的~
