### ISSUE TITLE
能否支持mermaid

### ISSUE THREAD

**Issue by ChloemoShaw** [akof1314/Wiz.Editor.md#169]
mermaid对于画图十分方便,有没考虑支持一下,在github有库,官网地址https://mermaidjs.github.io/

**Comment by heartnn** [comment]
貌似为知官方没支持，如果按照官方渲染的话，即使这个编辑器支持也没有用啊。

**Comment by akof1314** [comment]
是的，等官方支持了再支持

**Comment by ChloemoShaw** [comment]
那么暂时只能这样了。 heartnn 说的源代码是指html么？直接黏贴到笔记内容里面对么？

**Comment by heartnn** [comment]
源代码就是mermaid里写的源码，等官方支持了以后那个链接就可以不要了，这样有备无患，而且懒癌发作时，不愿意重新编辑笔记了。

相当于双重保险而已
三个反引号后面直接跟mermaid，许多支持的笔记软件或者编辑器都是用这种模式，以后官方支持的话应该也是这样的。

**Comment by ChloemoShaw** [comment]
好的理解了， heartnn ，好像生成的链接上面的图，会一直在样的，是么？即使关掉页面点击链接也在

**Comment by heartnn** [comment]
那会是一个很长的链接，链接里包含了整个mermaid的代码
