### ISSUE TITLE
字数统计功能

### ISSUE THREAD

**Issue by kyleinfo** [akof1314/Wiz.Editor.md#17]
在编辑状态下，wiz 自带的字数统计功能的按钮被隐藏了，因此希望能够在工具栏加入显示字数统计的按钮。

**Comment by kyleinfo** [comment]
关于字数统计的按钮如何显示，我考虑了三种方案，
第一种像其它工具栏按钮一样，点击时弹出显示，这样能够显示的内容最多，但这样不够便捷感觉似乎违背了设计的初衷；
第二种是在工具栏实时显示字数的变化，这种方式最便捷但似乎会影响性能；
第三种是在工具栏显示，但只有在保存时才改变现实的内容，个人感觉这种方式最平衡；

**Comment by akof1314** [comment]
@kyleinfo 感谢建议。先记录下。目前可以通过切换到阅读模式，来查看字数统计，再切换回去编辑。

**Comment by akof1314** [comment]
@kyleinfo 2.0版本已经加入这个功能
