### ISSUE TITLE
利用官方的编辑器添加附件后，在editor.md里打开会丢失链接

### ISSUE THREAD

**Issue by heartnn** [akof1314/Wiz.Editor.md#171]
也就是wiz://开头的链接会被丢掉，建议逻辑上修改一下，比如这个是编辑后的：

```
[![](index_files/30199484.png)](wiz://open_attachment?guid=a6ad830c-f7fa-49b4-a5c6-7d466bc28641)
```

`![](index_files/30199484.png)` 是编辑器默认保留的部分。

(20180831 编辑了一下issue，之前github把markdown自动识别了没显示出效果来~~)

**Comment by akof1314** [comment]
收到

**Comment by akof1314** [comment]
如果是用这种格式的话，那不会丢掉的，因为都是纯文本

**Comment by heartnn** [comment]
@akof1314 问题是官方可以插入附件，而咱们这个不行啊，如果能获取到附件的链接也好。

**Comment by akof1314** [comment]
刚提交了，解决了链接丢失问题，也解决了右侧打开链接。至于插件附件这个功能，以后再看看吧。。。哈哈哈

**Comment by heartnn** [comment]
给力，马上去试一下。
