### ISSUE TITLE
公式渲染问题

### ISSUE THREAD

**Issue by ChloemoShaw** [akof1314/Wiz.Editor.md#173]
# 在Wiz中的代码与在插件中的渲染结果不一样，如何解决？
代码如下
```
\begin{array} {{c|lcr}}
n & \text{Left} &\text{Center}&\text{Right} \\ 
\hline 
1&0.24 &1 & 125\\ 
2 & -1 & 189 &-8\\
3 & -20 & 2000 &1+10i
\end{array}
```
# 在Wiz中的渲染是如下图所示：
![](https://ws1.sinaimg.cn/large/69455243ly1fuwhr2q66oj20fk08hweo.jpg)
# 在插件中的渲染结果如下图所示：
![](https://ws1.sinaimg.cn/large/69455243ly1fuwhvmnpoyj20tq09ewfh.jpg)

**Comment by akof1314** [comment]
前面要加美元符号

**Comment by akof1314** [comment]
建议用标准做法，这样到时候拷贝到其他外部编辑器的时候，也能被识别

**Comment by ChloemoShaw** [comment]
恩嗯，知道的，我只是很奇怪Wiz居然支持这么大尺度的语法使得我没发现这么明显的问题
