### ISSUE TITLE
期待能有个导航, 像Vnote那样

### ISSUE THREAD

**Issue by xiao2752271456** [akof1314/Wiz.Editor.md#174]
![image](https://user-images.githubusercontent.com/30465802/44982928-0819a680-afaa-11e8-9790-cc77d19af6d1.png)

**Comment by ChloemoShaw** [comment]
有一个大纲不过不是固定的，是弹框

**Comment by xiao2752271456** [comment]
弹框我知道, 看是用着不方便呀

**Comment by ChloemoShaw** [comment]
是的，我也觉得固定的比较好尤其是很长的笔记

**Comment by akof1314** [comment]
收到

**Comment by xiao2752271456** [comment]
拜谢!!!
