### ISSUE TITLE
能否支持Kotlin语法格式

### ISSUE THREAD

**Issue by Lindroy** [akof1314/Wiz.Editor.md#175]
近年来Kotlin的运用越来越广，不得不说这真是一门相对不错的语言，所以希望能够支持Kotlin代码高亮，谢谢了。

**Comment by akof1314** [comment]
文本编辑区是支持的
` ```kotlin `
用这样子声明

**Comment by Lindroy** [comment]
试了一下，感觉不是太好看，不过还是谢谢了。
