### ISSUE TITLE
插件导致默认渲染结果的问题？

### ISSUE THREAD

**Issue by HuangXiaoKai** [akof1314/Wiz.Editor.md#181]
即使我将默认editor改成的内部编辑器，直接点开md文件，为知的渲染也会出现问题，出现一个很丑的渲染结果。而且这个渲染是和editor.md插件有关的，因为如果我更换插件的主题风格default/dark，这个默认渲染的背景也会跟着变。
![20181104_221415410_ios](https://user-images.githubusercontent.com/22166802/47970567-fce80300-e04c-11e8-9119-b919444024f5.jpg)

**Comment by akof1314** [comment]
现在插件不再更改为知的渲染了，请用新版。
