### ISSUE TITLE
同步显示问题

### ISSUE THREAD

**Issue by cqzhao** [akof1314/Wiz.Editor.md#19]
请问目前是按行数来同步显示的么？这样在头部插入[TOC]后 会出现预览同步错位的问题。

**Comment by akof1314** [comment]
嗯，目前是这样子的。

**Comment by yangcyyang** [comment]
有没有办法解决这个问题？

**Comment by eightHundreds** [comment]
我看其他md编辑器似乎是根据标题定位

**Comment by akof1314** [comment]
@cqzhao @yangcyyang @eightHundreds 2.0版本已经改成同步预览了
