### ISSUE TITLE
windows 4.13.2 无法编辑 markdown 笔记

### ISSUE THREAD

**Issue by aaazz47** [akof1314/Wiz.Editor.md#196]
不知道是不是新版为知笔记更新浏览器内核的原因啊，这次安装之后就没办法用这个插件打开 Markdown 笔记。
打开之后一片空白，标题栏显示的是一些参数。

【客户端平台及版本】：Windows 4.13.2
【问题现象】：markdown 编辑插件无法进入编辑，新打开的页面是一片空白
【尝试解决及结果】：尝试重新下载安装插件。【失败，问题未解决】
![批注 2020-02-21 165704](https://user-images.githubusercontent.com/19562000/75020042-ea593d80-54cc-11ea-8a0b-d472bd0b36e2.jpg)
![批注 2020-02-21 1657042](https://user-images.githubusercontent.com/19562000/75020054-ee855b00-54cc-11ea-96b0-72e1d4d973cf.jpg)

**Comment by aaazz47** [comment]
我这边北京电信似乎看不到上传的图片 github 用的不熟悉，不知道是不是上传图片方法有问题？
我在为知笔记的论坛有反馈供参考吧
https://support.qq.com/products/106842/post/158227581138997382/

**Comment by zydxhs** [comment]
Windows 4.13.4, 遇到了同样的问题。

**Comment by wanniwa** [comment]
我也遇到了同样问题

**Comment by bombah908** [comment]
客户端4.13.3
环境Win10x64
问题：同上

**Comment by Zwysilence** [comment]
客户端4.13.4
环境Win7 x64
问题：同上

**Comment by akof1314** [comment]
正在检查原因~~

**Comment by aaazz47** [comment]
> 
> 
> 已发布v2.8来适配为知4.13版本

感谢
更新之后我这边就没问题了
