### ISSUE TITLE
和为知笔记本身markdown支持问题

### ISSUE THREAD

**Issue by icemute** [akof1314/Wiz.Editor.md#2]
使用这个编辑器在编辑时可以预览editor.md的样式，可是保存后显示的是Wiz自己的markdown样式啊，而且Wiz的markdown支持还不完全  ，这不会出问题吗？？？

**Comment by akof1314** [comment]
不会出问题，因为markdown保存的都是纯文本，只是渲染表现的不同。暂时没有Wiz的markdown样式，因为考虑到目前仅Window端支持插件方式，更改了Window端样式，其他平台端也还是会显示不一样的。后面我会实现个替换wiz自身的Markdown样式方案，当然仅Window平台。

**Comment by akof1314** [comment]
不会出问题，因为markdown保存的都是纯文本，只是渲染表现的不同。暂时没有Wiz的markdown样式，因为考虑到目前仅Window端支持插件方式，更改了Window端样式，其他平台端也还是会显示不一样的。后面我会实现个替换wiz自身的Markdown样式方案，当然仅Window平台。

**Comment by icemute** [comment]
嗯~这个插件我很喜欢，加油更新^_^

**Comment by akof1314** [comment]
@icemute 已经支持替换默认渲染方式
