### ISSUE TITLE
是否支持mac版本

### ISSUE THREAD

**Issue by MerlinFeng** [akof1314/Wiz.Editor.md#204]
是否支持mac版本

**Comment by akof1314** [comment]
mac版本没有插件功能

**Comment by altairwei** [comment]
我维护的 [WizNotePlus](https://github.com/altairwei/WizNotePlus) 已经基本完成 Wiz.Editor.md 移植到 Linux/MacOS 客户端的工作，如果你需要使用可以关注下更新。
