### ISSUE TITLE
能否增加一个“内容目录”的快捷键

### ISSUE THREAD

**Issue by jiewangjs** [akof1314/Wiz.Editor.md#219]
添加新的标题后，内容目录不会更新

**Comment by altairwei** [comment]
我没明白你说的 “内容目录” 是什么功能？

**Comment by jiewangjs** [comment]
就是markdown编辑器界面右上方的一个按钮
![image](https://user-images.githubusercontent.com/11204422/103596794-b26ab580-4f39-11eb-806d-bf563bafe757.png)

**Comment by altairwei** [comment]
这个功能要你在 “实时预览” 状态下才看得见，而且应该是与预览中的标题同步的。

**Comment by jiewangjs** [comment]
> 这个功能要你在 “实时预览” 状态下才看得见，而且应该是与预览中的标题同步的。

![image](https://user-images.githubusercontent.com/11204422/103644373-3bf9a200-4f91-11eb-9392-23a2c20c5941.png)

你可能没有完全理解我的意思，图中的222标题并不会在navigation panel中显示，需要手动点击按钮更新。能否
1）自动更新
2）给目录按钮设个快捷键

**Comment by altairwei** [comment]
我明白了，你是把目录框固定了，所以目录不会更新。

**Comment by jiewangjs** [comment]
> 我明白了，你是把目录框固定了，所以目录不会更新。

写作的时候，很实用的功能。
