### ISSUE TITLE
希望能增加Mermaid支持，这样除了sequence和flowchat还可以使用gantt，编辑器将会和Typora一样强大了。

### ISSUE THREAD

**Issue by zgpnuaa** [akof1314/Wiz.Editor.md#222]
Typora非常好用，支持Mermaid，可以画甘特图。

**Comment by akof1314** [comment]
暂不考虑支持Mermaid，否则为知会渲染不了

**Comment by zgpnuaa** [comment]
> 暂不考虑支持Mermaid，否则为知会渲染不了

噢噢，好吧。

我自己试着实现一下支持Mermaid吧。
你有没有支持Mermaid的大致实现思路啊。

**Comment by akof1314** [comment]
参照Mermaid的示例，应该就可以很快接入

**Comment by zgpnuaa** [comment]
> 的

好的，我试试看，谢谢哈

**Comment by zgpnuaa** [comment]
> 参照Mermaid的示例，应该就可以很快接入

好的，谢谢哈，我试试看
