### ISSUE TITLE
无法页内锚点跳转

### ISSUE THREAD

**Issue by yinxufeng** [akof1314/Wiz.Editor.md#24]
在Editor.md的例子中输入：
\[锚点链接2](#图片 Images)” 能够跳转到`图片 Images`标题

**Comment by akof1314** [comment]
```
[锚点链接][anchor-id]

[anchor-id]: http://www.baidu.com/
```
锚点链接是这种方式

**Comment by yinxufeng** [comment]
我是想要实现页面内的跳转。点某个链接，跳到某个章节（标题）
我在https://pandao.github.io/editor.md/ 试过用
\[锚点链接](#图片 Images)” 能够跳转到`### 图片 Images`标题

**Comment by akof1314** [comment]
链接的打开方式被我改成新窗口打开了，以免当前笔记丢失。页面内跳转这种情况，确实是没有处理，我后面再给它加上。

**Comment by akof1314** [comment]
@yinxufeng 在https://pandao.github.io/editor.md/ 的哪个例子里面呢
