### ISSUE TITLE
用 Editor.md 编辑时自动全屏

### ISSUE THREAD

**Issue by jxiaoyu** [akof1314/Wiz.Editor.md#25]
![image](https://cloud.githubusercontent.com/assets/2398213/10068079/1c82fd36-62d4-11e5-8730-4432c8448f54.png)
现在用 Editor.md 编辑的时候，我需要手动把它全屏，不然的的话编辑区太小了。希望能加一个编辑时自动全屏的功能。

**Comment by akof1314** [comment]
@jxiaoyu 进入编辑的时候，手动按一下F11就可以全屏了，很快的。
