### ISSUE TITLE
插入本地图片的笔记分享后看不到图片

### ISSUE THREAD

**Issue by jxiaoyu** [akof1314/Wiz.Editor.md#26]
笔记插入本地图片后，分享链接，点链接进去看到的笔记没有图片，如下所示。
![image](https://cloud.githubusercontent.com/assets/2398213/10115664/0095f040-6443-11e5-96f4-7259cb59d474.png)

**Comment by akof1314** [comment]
@jxiaoyu 参见之前的ISSUE https://github.com/akof1314/Wiz.Editor.md/issues/12
