### ISSUE TITLE
对于指向已有笔记的链接，使用Editor.md编辑后链接会失效

### ISSUE THREAD

**Issue by ParadiseDS** [akof1314/Wiz.Editor.md#27]
![](http://img-storage.qiniudn.com/15-9-29/49306199.jpg)
这个链接是指向已有的一篇笔记的，wiz的功能，把笔记标题拖到编辑页里就好了，但是使用Editor.md编辑后保存该链接就会失效，转变为纯文本。
是不支持笔记链接吗？

**Comment by akof1314** [comment]
不能直接保存链接，需要用Markdown的语法来保存链接。

目前的操作方法可以为，右键已有的笔记，选择`高级`→`复制链接`，然后粘贴到Editor.md编辑器里面。

**Comment by ParadiseDS** [comment]
好的。。
