### ISSUE TITLE
预览窗口左右并不匹配，貌似是按照行数来的。那么能否在修改原文件后，在推送预览的时候关掉滚轴呢？

### ISSUE THREAD

**Issue by wangxiaodong3085** [akof1314/Wiz.Editor.md#29]
预览窗口左右并不匹配，貌似是按照行数来的。那么能否在修改原文件后，在推送预览的时候关掉滚轴呢？
RT

**Comment by akof1314** [comment]
@wangxiaodong3085 意思是说不同步滚动吗，有配置项，需要在插件目录里面文件去改。

**Comment by demonfchan** [comment]
同样有这个问题，内容多的时候，滚动到后面，错位问题比较严重。
右侧预览窗口的滚动控制，最好能够根据左侧的首行对应的预览行来控制同步。
如果有这个配置项的话，请告知一下具体应该怎么配置

**Comment by akof1314** [comment]
@wangxiaodong3085 @demonfchan 2.0版本已经改成同步预览了

**Comment by milo-wjh** [comment]
使用为知应用插件下载的2.5版本，也会出现这种情况，
左边滚到最下方了，右边预览的还处在中间位置，看不到最新输入内容
