### ISSUE TITLE
ToC目录生成的不对

### ISSUE THREAD

**Issue by huyihuigi** [akof1314/Wiz.Editor.md#30]
2级标题下的3级标题如果包含5级标题（我用的场景中没有4级标题），那么该3级标题之后的3级标题会跟2级标题对齐。

**Comment by akof1314** [comment]
@huyihuigi 嗯，是有这个问题，记录下了。

**Comment by babytoy2015** [comment]
使用wiz时，在编辑状态下能看到TOC生成的目录，但是不使用md编辑器时，看不到目录，这个是wiz的问题吗？

**Comment by akof1314** [comment]
@babytoy2015 要在阅读时也看到效果，需要开启替换为知渲染。

**Comment by Michael728** [comment]
很棒的插件!!!真心点赞！！！作者，我想请问，怎么更改为知的默认渲染啊？没你的好看啊……

**Comment by akof1314** [comment]
![image](https://cloud.githubusercontent.com/assets/2639552/11139813/d406f41a-8a0e-11e5-9fff-0bee69cb1291.png)
@Michael728 工具栏上有个选项按钮，可以进行设置

**Comment by Michael728** [comment]
@akof1314 但是保存笔记后，预览还是为知自带的效果了……

**Comment by akof1314** [comment]
@Michael728 需要重启为知笔记。
