### ISSUE TITLE
Katex渲染问题

### ISSUE THREAD

**Issue by arwenzhou** [akof1314/Wiz.Editor.md#31]
分别输入了
> $$X_1,..., X_N$$
> $$g_{(x)}$$

但是不出现渲染后结果，无论是在行内公式还是独立成行的公式
但是在katex官方网站可以正常显示

**Comment by akof1314** [comment]
@arwenzhou 因为$$X_1,..., X_N$$解析错了，导致后面也出错，这个问题先记录下。

**Comment by akof1314** [comment]
见 #11
