### ISSUE TITLE
每次打开会有一段时间无法键入

### ISSUE THREAD

**Issue by GuihaiHU** [akof1314/Wiz.Editor.md#33]
你好！每次使用它编辑的时候，除了回车键，其他按键都无法显示，过了一段时间后恢复

**Comment by FleecyMirror** [comment]
我也经常遇到这个问题

**Comment by akof1314** [comment]
我这边不会发现呢，是什么环境呢？

**Comment by GuihaiHU** [comment]
win10家庭版

--
发自我的ONEPLUS智能手机

WuHuan <notifications@github.com>编写：

**Comment by akof1314** [comment]
暂无法测试到
