### ISSUE TITLE
公式渲染问题

### ISSUE THREAD

**Issue by fanfzhang** [akof1314/Wiz.Editor.md#34]
写一个多行公式，预览时没有问题，用为知打开阅读的时候有问题。
![1](https://cloud.githubusercontent.com/assets/13691016/11760720/c9e17080-a0e0-11e5-87f1-4f1806dfbe57.PNG)
阅读时：
![2](https://cloud.githubusercontent.com/assets/13691016/11760726/eb5fdf62-a0e0-11e5-921b-2860135246fa.PNG)
还有，这里写的是行内公式，预览时没有问题。
![3](https://cloud.githubusercontent.com/assets/13691016/11760732/1c26e276-a0e1-11e5-8774-706983d70415.PNG)
阅读时就变成下面这样：
![4](https://cloud.githubusercontent.com/assets/13691016/11760735/34d32f1e-a0e1-11e5-9a25-0d5e25f2cc7b.PNG)

**Comment by fanfzhang** [comment]
我知道原因了，因为上面我使用的是为editor.md风格渲染，在阅读时显示就会出错。
把渲染风格改为，为知风格，那么首先公式的书写方法要稍微改一下，行内公式要写为$公式$，在预览的时候是看不到渲染结果的。。。。这样写在手机端和电脑端阅读时是好的。
好纠结。

**Comment by akof1314** [comment]
@fanfzhang 嗯，插件跟为知自带的公式书写规则和渲染方式是不同的，这点会比较麻烦一些。

**Comment by linnEn** [comment]
遇到一个问题，在编辑界面 输入如： $$\sum_{k=1}^N k^2$$ 这种符号，不能成功渲染。

**Comment by HiYu** [comment]
不仅公式问题emoji、todolist都存在这样的问题，在编辑预览是好好的，到阅读模式下就不行了

**Comment by akof1314** [comment]
@linnEn 见 #11

**Comment by akof1314** [comment]
@HiYu 是不是阅读模式，没有选择 editor.md 渲染

**Comment by HiYu** [comment]
您好，
     很高兴收到您回复。选择的是editor.md格式。我用官方的一个tex公式的例子
https://pandao.github.io/editor.md/examples/katex.html做了测试，结果是，wiz的阅读模式和
editor.md的预览模式显示结果又比较大差别。附图中，左图是预览结果，可以发现多行公式是可以正常显示的，但是，在wiz的阅读模式下却不能渲染如右图。

​

2016-07-03 11:23 GMT+08:00 WuHuan <notifications@github.com>:

**Comment by akof1314** [comment]
@HiYu 用邮件回复，看不到图，可以在github贴一下图吗

**Comment by akof1314** [comment]
2.0版本数学公式已经改成MathJax
