### ISSUE TITLE
工具栏问题

### ISSUE THREAD

**Issue by shusoar** [akof1314/Wiz.Editor.md#35]
工具栏 有default和lite 风格

1. 若不想显示工具栏 如何设置呢？或者说工具栏/设置窗口 可以用快捷键调出 临时/浮动显示； 平时书写时不显示。

  >这样简单节省空间； 因为Wiz上面有标题栏-工具栏 和页面tab，下面再加上出编辑markdown时的工具栏  纵向空间就更小了。

2. 工具栏上是否可以添加关于正在编写文件的 大纲的按钮？  因为编辑时有时候想通过大纲快捷的跳到特定位置 ；如果点击就浮动显示大纲， 那就太好了。

- 第一点没有也不要紧 第二点真的想要。

**Comment by akof1314** [comment]
@shusoar 
建议很不错，收到~

**Comment by akof1314** [comment]
@shusoar 2.0版本已经加入大纲功能
