### ISSUE TITLE
在列表内容中使用代码块后，编辑器的高亮会挂掉

### ISSUE THREAD

**Issue by ParadiseDS** [akof1314/Wiz.Editor.md#37]
![](http://i4.tietuku.com/8bebc6c9d5393542.png)
like this
在一个有序列表（无序也是一样问题）的子内容里插入一个代码块，即整个代码块前包含两个空格，下面的语法高亮就会挂掉。

**Comment by akof1314** [comment]
收到~

**Comment by akof1314** [comment]
Fixed [https://github.com/akof1314/Wiz.Editor.md/issues/102](https://github.com/akof1314/Wiz.Editor.md/issues/102)
