### ISSUE TITLE
英文引号被渲染为中文引号

### ISSUE THREAD

**Issue by AbnerGong** [akof1314/Wiz.Editor.md#38]
英文引号应该是"这样的"，引号与字之间没有空格
但是在编辑器里面，英文引号渲染出来的全部都是中文的右引号，于是左引号跟汉字之间有很大的空格，而右引号与汉字之间没有空格，所以看起来完全不对称
双引号和单引号都有这个问题
求解决这个问题，多谢

PS：博主玩kof97,98还是02

**Comment by akof1314** [comment]
@AbnerGong 谢谢指出这个问题，是有存在这个问题。

PS:都有玩，都很菜~
