### ISSUE TITLE
引文部分能否不用斜体，而用正常格式。无法区分引文中的斜体与正常正文。

### ISSUE THREAD

**Issue by ChloemoShaw** [akof1314/Wiz.Editor.md#40]
在很多英文作品中斜体都表示著作书籍，渲染后全部斜体几乎都看不出哪些是书籍名称和正文。如果要区分引文和正文，可以从颜色和字体上改变，但是最好不要改成markdown可编辑的文字形式否则可能会起冲突而丢失一些编辑信息。麻烦帮忙解决一下，在wiz风格和md渲染风格之间切换很痛苦。

**Comment by akof1314** [comment]
引文格式要修改的话，可以修改CSS样式。这里我先标记下。
风格切换很麻烦的话，可以直接设置用md来渲染。

**Comment by demonfchan** [comment]
如果会css的话，可以修改My Knowledge\Plugins\Wiz.Editor.md\Editor.md\lib\codemirror\theme目录下你选择的风格对应的css，修改.cm-quote这个

**Comment by ChloemoShaw** [comment]
还是建议一下作者最好不要用有特定意义的格式作为引言部分格式，这样插件用起来会更加顺手些。毕竟用md做笔记的不一定都是程序员不一定都会用CSS，就算会也觉得麻烦。
