### ISSUE TITLE
在代码块里面貌似没有去掉 emoji 的解析呢.....

### ISSUE THREAD

**Issue by ParadiseDS** [akof1314/Wiz.Editor.md#42]
![image](https://cloud.githubusercontent.com/assets/3424318/12450707/40eed444-bfc0-11e5-8f68-eca8690396af.png)

如红色方框里所示，在一个代码块里面，两个冒号及其中间的部分被解析了，看了下链接貌似是 emoji，没怎么用过 emoji 也不清楚.....

如果是 bug 的话，希望能够解决，现在已经把所有渲染风格都换成 editor.md 了....谢谢~

**Comment by akof1314** [comment]
可以先在配置里面，把emoji表情关闭掉。
