### ISSUE TITLE
如何使用，为啥我安装了之后，无法找到Editor.md这个程序？

### ISSUE THREAD

**Issue by Mr-wangyong** [akof1314/Wiz.Editor.md#45]

**Comment by John-Chan** [comment]
正好昨天也装了一下这个插件，我摸索出一个用法：你新建一篇笔记，标题以`.MD`结尾。然后按照MARKDOWM语法写笔记，写完后点击保存才能看见效果。

**Comment by John-Chan** [comment]
另外，也可以点击笔记左上角的编辑按钮（下拉按钮），选则`Editor.md编辑器`

**Comment by JMingZI** [comment]
+1

**Comment by akof1314** [comment]
新建.md笔记，选择Editor.md编辑器编辑。
