### ISSUE TITLE
Linux版本下编辑的md 在windows版下用Editor编辑会一堆空行

### ISSUE THREAD

**Issue by zbjdonald** [akof1314/Wiz.Editor.md#49]
您好，我在linux下编辑的markdown 用windows版的此Editor 会每隔一行多一行空行像这样

```
haha

haha
```

Linux版正常了就

```
haha
haha
```

**Comment by akof1314** [comment]
用为知自带编辑器编辑的Markdown不是以文本方式保存的，所以跟这个插件不太兼容。

**Comment by zbjdonald** [comment]
@akof1314 谢谢回复，已经用马克飞象 + 印象笔记组合。
