### ISSUE TITLE
替换wiz默认的渲染方式后主题颜色未改变

### ISSUE THREAD

**Issue by kyleinfo** [akof1314/Wiz.Editor.md#5]
1.3 版替换了Wiz自带渲染方式，但是假如将 Wiz.Editor.md 的主题设置为 dark，然后让笔记以保持阅读模式呈现时，笔记的配色依旧是默认的配色

**Comment by ribber** [comment]
我也发现这个问题了。希望楼主能够解决

**Comment by akof1314** [comment]
目前的主题设置仅在编辑时，进行影响。 既然有需要在阅读时，也保持这个主题样式的话，那么我将会在下一版本添加这个功能。

**Comment by ribber** [comment]
我更新了您的自定义主题，好像设置阅读时样式还是不起作用，就是设置成dark还是default

**Comment by akof1314** [comment]
@ribber 功能还未完成，完成的话，将会发布个版本。

**Comment by akof1314** [comment]
1.4 版本修复
