### ISSUE TITLE
公式渲染问题 如累加符号 $$\sum_{k=1}^N k^2$$

### ISSUE THREAD

**Issue by linnEn** [akof1314/Wiz.Editor.md#53]
当前设置：默认编辑器设置为 editor.md  编辑界面中的渲染风格 也设置为 editor.md.
遇到的问题： 输入如 $$\sum_{k=1}^N k^2$$ 这种公式，在右侧的预览界面，不能显示。

**Comment by JamesBond008** [comment]
我也遇到这种问题了，公式不能实时预览，保存后在可以显示

**Comment by akof1314** [comment]
暂时有这个bug，带下划线的，见 #11
