### ISSUE TITLE
编辑器和渲染样式字体大小修改

### ISSUE THREAD

**Issue by simoxi** [akof1314/Wiz.Editor.md#56]
请问，怎么修改样式文件可以把编辑器和渲染样式的字体变大些？现有字体太小了。。。。

**Comment by simoxi** [comment]
还有就是请问如何取消渲染后标题下的下划线？

**Comment by akof1314** [comment]
这都需要修改`Plugins\Wiz.Editor.md\Editor.md\css`里面的CSS样式
