### ISSUE TITLE
某些情况下排版有问题

### ISSUE THREAD

**Issue by deathrush** [akof1314/Wiz.Editor.md#57]
代码:
- 你可以这样列出本机电脑的MAC和IP地址：

``` powershell
$ComputerName = ''
[System.Net.Dns]::GetHostAddresses($ComputerName)
```
- 仅获取IPV4地址：

``` powershell
$ComputerName = ''
[System.Net.Dns]::GetHostAddresses($ComputerName) |
Where-Object {
   $_.AddressFamily -eq 'InterNetwork'
} |
Select-Object -ExpandProperty IPAddressToString
```
- 仅获取IPV6地址：

``` powershell
$ComputerName = ''
[System.Net.Dns]::GetHostAddresses($ComputerName) |
Where-Object {
  $_.AddressFamily -eq 'InterNetworkV6'
} |
Select-Object -ExpandProperty IPAddressToString
```

Wiz.Editor.md的排版：
![1](https://cloud.githubusercontent.com/assets/10840992/16640035/7fdc5140-4427-11e6-9983-8e82aca95b2a.jpg)

MdCharm的正确排版：
![2](https://cloud.githubusercontent.com/assets/10840992/16640255/1e62267c-4429-11e6-86aa-12bf337b1a05.jpg)

**Comment by akof1314** [comment]
列表下的代码排版有点问题，先在列表与代码之间空行，如下：

![2016-07-07_194650](https://cloud.githubusercontent.com/assets/2639552/16652253/dded0546-447b-11e6-9a8f-fe761f50a145.png)

**Comment by deathrush** [comment]
3ks
