### ISSUE TITLE
插入的图片经常无法显示

### ISSUE THREAD

**Issue by BruceZP** [akof1314/Wiz.Editor.md#62]
如题，经常出现插入的图片过段时间就不能够很好的显示。
![image](https://cloud.githubusercontent.com/assets/16569281/17285625/6a9ed2fc-57f6-11e6-8272-c384c087ef8e.png)
具体表现如图。

**Comment by akof1314** [comment]
所有的文章都是这样过段时间就无法显示吗

**Comment by BruceZP** [comment]
不是所有的，最近在wiznote的百度贴吧中也发现有人有相同的问题，不知道是不是wiznote存在的bug。

**Comment by tttMelody** [comment]
我也遇到这样的问题了,很郁闷的问题

**Comment by akof1314** [comment]
绝对不要两个编辑器混合着使用，为知默认的不是标准的markdown存图片方式。

**Comment by BruceZP** [comment]
我的是没有混着用的，wiz的markdown很不好用，我基本都是不用的。

**Comment by akof1314** [comment]
@BruceZP 暂时无法发现是什么原因，我这边是正常

**Comment by tttMelody** [comment]
@akof1314 有时候电脑客户端能显示图片 ios端的图片就挂了..可能是为知自己的问题?

**Comment by akof1314** [comment]
@tttMelody 为知PC端和IOS端显示Markdown图片的方式不一样，所以才导致这样子。

**Comment by akof1314** [comment]
使用新版
