### ISSUE TITLE
原来用为知默认编辑器插图用editor编辑保存图片消失

### ISSUE THREAD

**Issue by tttMelody** [akof1314/Wiz.Editor.md#63]
比较蛋疼的问题,原来用为知默认编辑器编辑的markdown,图片插入是直接插入的(就是在编辑的时候也可以直接看到图片),这些笔记要是那这个编辑器打开了,然后再保存图片就会消失.而且在为知的移动端,有的图片也无法显示

**Comment by akof1314** [comment]
绝对不要两个编辑器混合着使用，为知默认的不是标准的markdown存图片方式。

**Comment by tttMelody** [comment]
发现了 但是有时候就是一顺手直接点了编辑....

**Comment by akof1314** [comment]
@tttMelody 2.0版本已经可以兼容为知的插入图片方式了
