### ISSUE TITLE
工具栏无法显示

### ISSUE THREAD

**Issue by AStupidBear** [akof1314/Wiz.Editor.md#64]
![image](https://cloud.githubusercontent.com/assets/16422976/17443237/15ad7c0c-5b6c-11e6-9459-bfb245cc0afe.png)

**Comment by akof1314** [comment]
操作系统是什么，为知是哪个版本呢

**Comment by AStupidBear** [comment]
抱歉打扰了，重启电脑好了。 win10，最新wiz
