### ISSUE TITLE
editor预览的和保存后的实际效果不一样。

### ISSUE THREAD

**Issue by fpk2014** [akof1314/Wiz.Editor.md#65]
![default](https://cloud.githubusercontent.com/assets/16163903/17467822/b91843d8-5d54-11e6-965d-79f88df5bd42.PNG)

![1](https://cloud.githubusercontent.com/assets/16163903/17467824/bf400020-5d54-11e6-8cc1-6e6c7a64e93d.PNG)

**Comment by akof1314** [comment]
保存后预览， 默认是为知自带的渲染方式，可以改为editor.md的渲染方式。

**Comment by fpk2014** [comment]
好的，谢谢
