### ISSUE TITLE
问下作者有没有无格式黏贴的快捷键?

### ISSUE THREAD

**Issue by tttMelody** [akof1314/Wiz.Editor.md#66]
有时候复制代码,代码带格式的话,经常前面一长串html,有没有就比如说像ctrl+shift+v 是无格式黏贴的呢

**Comment by akof1314** [comment]
@tttMelody 快捷键ctrl+shift+v 就是无格式粘贴了。

**Comment by tttMelody** [comment]
@akof1314 作者你好 我Intellij IDEA 复制代码到editor中 ctrl+shift+v  还是显示这一堆
<pre style="background-color:#2b2b2b;color:#e2e2e2;font-family:'Monaco';font-size:14.3pt;">proxy.doSomething( "Finsh" );</pre>

**Comment by tttMelody** [comment]
![image](https://cloud.githubusercontent.com/assets/15643702/17723278/712442a2-646b-11e6-931f-e83141d081fe.png)

**Comment by akof1314** [comment]
@tttMelody 你用chrome打开插件目录下的index.html，在里面试试看。

**Comment by tttMelody** [comment]
@akof1314  实测快捷键在index.html下可行,但是在为知笔记中不行,可能是由于什么原因的?

**Comment by tttMelody** [comment]
@akof1314  请问一下快捷键可以在哪个js或者哪个文件中自定义吗

**Comment by tttMelody** [comment]
@akof1314 我想我知道为啥有时候图片会显示不出来了,就是比如我引用了外面网址的一张图片,在没有联网的情况下,图片是出不来的,这个有办法解决吗?

**Comment by akof1314** [comment]
无格式快捷键暂不支持更改~   外部网址的图片，是没有保存进为知笔记内部的，所以没法显示。

**Comment by tttMelody** [comment]
@akof1314 
谢谢作者,其他的快捷键在哪里更改呢?哪里更改?话说可以做到保存到本地吗?
