### ISSUE TITLE
GFM 的代码高亮功能支持 VimL 语言吗

### ISSUE THREAD

**Issue by tnie** [akof1314/Wiz.Editor.md#68]
作者描述“支持通用 Markdown / CommonMark 和 GFM (GitHub Flavored Markdown) 风格的语法”，想确认是支持三者的混用，还是支持三者之间的切换？另外，我在使用时并不能正确支持对 .vimrc 配置文件的语法高亮，而 GFM 本身是支持的（VimL）。是需要另外在哪里设置吗？

**Comment by akof1314** [comment]
语法是有支持，但是代码的高亮不是使用GitHub那种实现，而是使用 https://github.com/google/code-prettify ，所以暂时没有VimL。
