### ISSUE TITLE
global模式为什么不起作用？

### ISSUE THREAD

**Issue by stevenluan07** [akof1314/Wiz.Editor.md#7]
不安装Notes.markdown，在浏览界面（不是编辑界面）打开md文件，为什么editor.md不能进行解析？

**Comment by akof1314** [comment]
@stevenluan07 默认不替换Wiz的解析，打开方法为：用Editor.md编辑器打开一篇md文章，在工具栏→“选项”，设置渲染风格，选中"Editor.md风格“，重启为知笔记即可。
