### ISSUE TITLE
关于图片有时候加载不出来

### ISSUE THREAD

**Issue by tttMelody** [akof1314/Wiz.Editor.md#70]
引用外部图片的url的时候,没有网络的时候图片貌似会加载不出来,自己的截图什么的传上去貌似没有问题.

**Comment by akof1314** [comment]
外部网址的图片，是没有保存进为知笔记内部的，所以没法显示。

**Comment by tttMelody** [comment]
@akof1314 wizi居然不收费不能用了....难过

**Comment by tttMelody** [comment]
@akof1314 这个神一样好用的编辑器
