### ISSUE TITLE
编辑区和预览区显示的内容不对应

### ISSUE THREAD

**Issue by demolpc** [akof1314/Wiz.Editor.md#72]
拖动编辑区的滚动条，在预览区显示的不是对应的内容，请帮忙解决。

**Comment by akof1314** [comment]
是使用的最新版吗？可以截图看看吗？

**Comment by demolpc** [comment]
是最新版的，github上有人提了一样的问题。



lipengcheng610@126.com
 
发件人： WuHuan
发送时间： 2016-10-09 08:47
收件人： akof1314/Wiz.Editor.md
抄送： demolpc; Author
主题： Re: [akof1314/Wiz.Editor.md] 编辑区和预览区显示的内容不对应 (#72)
是使用的最新版吗？可以截图看看吗？

**Comment by akof1314** [comment]
我这边的长文本是正常的，可否将你的测试文本发我一下呢

**Comment by demolpc** [comment]
发到你新浪邮箱了



lipengcheng610@126.com
 
发件人： WuHuan
发送时间： 2016-10-09 12:29
收件人： akof1314/Wiz.Editor.md
抄送： demolpc; Author
主题： Re: [akof1314/Wiz.Editor.md] 编辑区和预览区显示的内容不对应 (#72)
我这边的长文本是正常的，可否将你的测试文本发我一下呢

**Comment by HuangXiaoKai** [comment]
我出现类似问题，wiznote上刚刚下载的，显示版本v2.0。发现：
拖动预览区，编辑区随动正常
拖动编辑区，开始10%部分预览区正常，编辑区再往下拉预览区跳回顶端不再动。

**Comment by akof1314** [comment]
已发现问题，正在修改~

**Comment by yearnfree** [comment]
您好, 编辑区和预览区显示的内容有的时候，还是不对应；多次测试后，发现文章内容超过310行左右的时候，就会不同步，右侧预览区域直接跳到了顶部开始位置；不知道您电脑上是不是这种情况。PS：Wiz.Editor.md已更新到ver 2.1, 笔记版本：V4.2.691

**Comment by akof1314** [comment]
@yearnfree 可以将测试文本发送到我邮箱下吗，好做测试。
