### ISSUE TITLE
预览区滚动条回滚

### ISSUE THREAD

**Issue by pot-code** [akof1314/Wiz.Editor.md#73]
之前版本预览区跟不上编辑区的滚动，这个版本加长了编辑区的滚动条，让预览区得以往下继续滚动。但是在编辑区持续往下滚动会导致预览区的滚动条开始往上滚动，而且幅度很大。

更新：文本内容很长时会容易出现，较短的就没问题。
16/10/11更新：并非长文本一定会触发，只有末尾空行大于（包含）2行时会引发回滚

**Comment by akof1314** [comment]
@pot-code 发现了这个问题，可以提供下测试文本吗？
