### ISSUE TITLE
代码折叠功能快捷键没有作用？

### ISSUE THREAD

**Issue by larrymars** [akof1314/Wiz.Editor.md#77]
在为知笔记里，使用这个插件，编辑器为Editor.md，200行的一段代码，使用CTRL+Q的快捷键进行代码折叠，没有效果，请问这个要如何使用？

**Comment by akof1314** [comment]
@larrymars 这个你要在左侧有箭头的那一行，用Ctrl+Q才能折叠。如果左侧没有小箭头，说明不可以折叠。
