### ISSUE TITLE
启用Editor风格作为为知阅读区，KaTeX表达式报错

### ISSUE THREAD

**Issue by ribber** [akof1314/Wiz.Editor.md#8]
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype. katex.min.js:1
Uncaught ParseError: KaTeX parse error: KaTeX doesn't work in quirks mode. katex.min.js:1

**Comment by akof1314** [comment]
@ribber 使用的是Master分支代码的话，可以将笔记用 Editor.md编辑器 打开，重新保存一下，就会修复所报的这个错误。

**Comment by ribber** [comment]
@akof1314  非常感谢！
