### ISSUE TITLE
新版本WIZ-4.5.2正式版,已经完全不能使用Wiz.Editor.md了

### ISSUE THREAD

**Issue by lfb511** [akof1314/Wiz.Editor.md#82]
请求更新一下，已经找不到Wiz.Editor编辑的按钮了

**Comment by akof1314** [comment]
@lfb511 正在等待官方发布新的开发文档~

**Comment by RoamIn** [comment]
- 原来已不能使用了

**Comment by akof1314** [comment]
@lfb511 @RoamIn 目前代码仓库已更新，可以用在4.5.2版本了，晚些时候会发布新版本。

**Comment by RoamIn** [comment]
我也发现为知自带 MarkDown 了 ，同样是保存为 .md，然后保存预览就可以了，基本满足我的需求了，虽说样式丑了点，但也还好。
上周也了解了一下，发现写个基于 VueJS 的 Web 实时预览还是很简单的，解析就行，外加样式，GitHub 的样式也有，哈哈，抽出来就行。想要 GitHub 的解析方式，它官方也提供接口，虽然它是基于 Ruby 的。
不过还是谢谢提醒！~

**Comment by busyluo** [comment]
@RoamIn 那个不是早就有的吗，关键是不能实习预览啊。

**Comment by RoamIn** [comment]
我不知道，我百度，说是下插件，然后就跑这来了....应该是之前没保存预览，所以没发现...

**Comment by akof1314** [comment]
已经发布新版本
