### ISSUE TITLE
编辑模式下右侧预览区标题显示不正常

### ISSUE THREAD

**Issue by tigerloveu** [akof1314/Wiz.Editor.md#84]
要加空格吗？
# 1
#1111
##3333
![wizmd](https://cloud.githubusercontent.com/assets/18712080/20858591/059d5ace-b983-11e6-8f6b-62a6bd1ce837.png)

**Comment by akof1314** [comment]
目前需要加空格

**Comment by tigerloveu** [comment]
了解，谢谢
