### ISSUE TITLE
设置editor.md风格无效！

### ISSUE THREAD

**Issue by lutianfei** [akof1314/Wiz.Editor.md#86]
为知笔记版本4.5.5，Wiz.Editor.md 2.1 设置改成editor.md风格并不行！
而且语法上也有一些，兼容问题，是否可以和为知笔记沟通下，建议采用一套渲染模板，否则很别扭啊！！！

**Comment by akof1314** [comment]
语法上可以说下哪些问题吗？

**Comment by lutianfei** [comment]
我现在知道的就是
脚注功能
checkbox功能
```代码代码功能，在wiz.editor.md预览的时候可紧贴前一个列表（“*”）段落，但在wiz阅读模式下似乎，无法渲染出代码样式

**Comment by akof1314** [comment]
嗯，因为底层并不一致，所以渲染也不同，但是语法大体是一样的。目前editor.md风格暂时失效，正在修改。

**Comment by akof1314** [comment]
新版本2.2刚发布，可以试下还是否有这问题。

**Comment by akof1314** [comment]
新版本2.2刚发布，可以试下还是否有这问题。wiki说明 [阅读模式下Editor.md渲染风格](https://github.com/akof1314/Wiz.Editor.md/wiki/%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%E4%B8%8BEditor.md%E6%B8%B2%E6%9F%93%E9%A3%8E%E6%A0%BC)
