### ISSUE TITLE
编辑框和实时预览框无法同步显示问题

### ISSUE THREAD

**Issue by lutianfei** [akof1314/Wiz.Editor.md#87]
在拖动实时预览框的时候是可以正常同步显示的
在拖动编辑框的时候预览框自动跳到最开始部分~~~~！！！

**Comment by akof1314** [comment]
@lutianfei 测试文本可以发我邮箱下吗？

**Comment by ahau1928** [comment]
我的一直不能同步滚动，不管是以前老版为知笔记客户端+老版Editor.md还是最新的为为知4.5.6 + Editor.md v2.1都不行；
左侧编辑区滚动，右侧预览区就立马回到顶端不动；
右侧预览区滚动，左侧根本不动；
左侧拖动滚动条，右侧刚开始往下滚动一点点，然后立马回到顶端不动；
右侧拖动滚动条，左侧只能根据大标题的位置来跳动，如果没有大标题，则也不会动；
我是Win10系统1607版本

**Comment by akof1314** [comment]
新版本2.2刚发布，可以试下还是否有这问题。

**Comment by akof1314** [comment]
@AriaLyy 测试文本可以提供下吗？
