### ISSUE TITLE
之前用其他外部编辑器编辑的MD文档，用Wiz.Editor.md打开会出现很多空行

### ISSUE THREAD

**Issue by NoAnyLove** [akof1314/Wiz.Editor.md#88]
RT

之前用的外部编辑器，比如EverEdit或者Notepad++，创建或者编辑的MD文档，之后用Wiz.Editor.md打开，会出现很多多余的空行。

比如，新建一个MD文档，用Notepad++编辑，写入如下内容：

```
# 这是标题

你好，这是测试文档

测试第二行

测试第三段
```

保存后，再用Wiz.Editor.md打开，效果如下图：

![screenshot](https://cloud.githubusercontent.com/assets/1233483/21249429/eb74364e-c30b-11e6-9f61-8b0fe938415f.png)

因为有很多以前用其他编辑器创建的MD文档，如果要用Wiz.Editor.md进行编辑，都会出现这种问题，需要手动删除和调整，非常麻烦，特别是有代码的情况下。此外，也使得混用编辑器会出现问题。

**Comment by akof1314** [comment]
收到

**Comment by akof1314** [comment]
新版本2.2刚发布，可以试下还是否有这问题。

**Comment by NoAnyLove** [comment]
已测试，不会出现这个问题了。非常感谢。
