### ISSUE TITLE
自动保存，无法放弃修改

### ISSUE THREAD

**Issue by NoAnyLove** [akof1314/Wiz.Editor.md#89]
用Wiz.Editor打开文档后，所做的修改会自动保存。之前的版本中好像需要点击“保存”图标之后才会生效，现在不知道为什么会自动保存（刚升级到了4.5.5）

有些时候做了误操作，本来想放弃更改，结果关闭Wiz.Editor，所做的更改就自动保存了，没有弹出对话框询问是否要保存。

特别是在配合issue#88的问题，如果一不小心打开了以前用其他编辑器编辑的MD文档，就只能从历史版本中进行恢复。之前尝试过在这种情况下点击Wiz.Editor.md中的撤销按钮，结果撤销效果就是直接变成空文档，再一关闭Wiz.Editor，文档内容全消失了，欲哭无泪，只有找历史版本恢复回来。

**Comment by akof1314** [comment]
因为4.5版本，更改了关闭标签的弹出对话框反馈，使得对话框失效。我正在修改这个bug，下个礼拜发布。

**Comment by akof1314** [comment]
新版本2.2刚发布，可以试下还是否有这问题。

**Comment by NoAnyLove** [comment]
已测试，不会出现这个问题了。非常感谢。
