### ISSUE TITLE
关于TOC和同步拖动的BUG

### ISSUE THREAD

**Issue by FPGA1988** [akof1314/Wiz.Editor.md#91]
# 1 关于目录TOC的bug
我的md文件第一行是一个无序列表：
- 参考文献 ：数字VLSI芯片设计第八章-单元表征
    
然后回车之后如果直接在第二行输入```[TOC]```则预览区无法识别出目录，直接显示[TOC]，需要在第一行后空一行之后才行，目测这里检测换行符等有问题？
# 2 关于拖动的bug
 - 编辑区和实时预览区的和 #87 中的描述差不多，我这边发现的是如果我第一行是无序列表，第二行是[TOC]，后面再跟一大堆文档，那么左边滑动，右边预览区无法跟随；
 - 如果第一行换成强调的**粗体**，其他不改变，则能正常上下滑动

ps : 版本都是最新的

**Comment by akof1314** [comment]
1. 是要空行的，才好识别；
2. 新版本2.2刚发布，可以试下还是否有这问题。
