### ISSUE TITLE
请问有哪些可用的快捷键

### ISSUE THREAD

**Issue by itstamen** [akof1314/Wiz.Editor.md#98]
# 非常好用，爱！
# 请问编辑器有哪些可用的快捷键， 
  看更新日志说有丰富的快捷键，但Ctrl+F ,Ctrl+R 这些快捷键好像都不可以用。

**Comment by akof1314** [comment]
快捷键在工具栏右侧的`使用帮助`，有些被为知拦截。

**Comment by akof1314** [comment]
[键盘快捷键](https://github.com/akof1314/Wiz.Editor.md/wiki/Keymap)
