### ISSUE TITLE
标题相同时跳转的bug

### ISSUE THREAD

**Issue by pot-code** [akof1314/Wiz.Editor.md#99]
两个同一标题级别（不同级别也会发生）下出现相同子标题时，点击第二个的子标题，会跳转到第一个的子标题下。
示例结构如下：
- 一级标题1
-- 二级标题
- 一级标题2
-- 二级标题

两个二级标题的名字相同，点击“一级标题2“下的二级标题会跳转到“一级标题1”下的二级标题处。
这只是针对同一级标题下的子标题而言，实际测试标题级别不同，但是名字相同也会出现此问题

**Comment by akof1314** [comment]
收到
